### ISSUE TITLE
[bump] susfs 1.5.2 update is out, will you update it?

### ISSUE THREAD

**Issue by whyakari** [dev-sm8350/kernel_oneplus_sm8350#2]
https://gitlab.com/simonpunk/susfs4ksu/-/tree/kernel-5.4?ref_type=heads

**Comment by Madara273** [comment]
Thanks 👍

пт, 13 груд. 2024 р., 20:52 користувач Shoiya Akari <
***@***.***> пише:

**Comment by whyakari** [comment]
I tried 1.5.2 but there are some errors in the compilations:- and another one I managed to build, but bootloop

**Comment by TogoFire** [comment]
No tag was created for the current version. Therefore, it wasn't released. Use only the release tag, or you'll end up with many unnecessary bugs and headaches. Simonpunk himself has already mentioned this
